# Default values for ${CHART_NAME}.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: <repository image>
  tag: <image tag>
  pullPolicy: <IfNotPresent|Always>

nameOverride: "${CHART_NAME}"
fullnameOverride: "${CHART_NAME}"

# ---------------------------------------------
#                 service
# ---------------------------------------------
service: {}
# # ClusterIP
#  type: ClusterIP
#  port: 8107
# # NodePort
#  type: NodePort
#  nodePort: 30000~31276


# ---------------------------------------------
#                 ingress
# ---------------------------------------------
ingress:
  enabled: false

# ---------------------------------------------
#          pod environment variable
# ---------------------------------------------
env: []
#  - name: JAVA_OPTS
#    value: -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Asia/Shanghai

# ---------------------------------------------
#               pod resources
# ---------------------------------------------
resources: {}
#   limits:
#     cpu: 4
#     memory: 2Gi
#   requests:
#     cpu: 4
#     memory: 2Gi

# ---------------------------------------------
#                 pod probes
# ---------------------------------------------
probes: {}
# livenessProbe:
#   httpGet:
#     path: /info
#     port: 8107
#   initialDelaySeconds: 60
#   timeoutSeconds: 5
#   failureThreshold: 12
# readinessProbe:
#   httpGet:
#     path: /info
#     port: 8107
#   initialDelaySeconds: 60
#   timeoutSeconds: 5
#   failureThreshold: 12

# ---------------------------------------------
# pod schedule nodeSelector|tolerations|affinity
# ---------------------------------------------
nodeSelector: {}
#  attribute=dev

tolerations: []
#  - key: "attribute"
#    operator: "Equal"
#     value: "dev"
#     effect: "NoSchedule"

affinity: {}
#  nodeAffinity:
#    preferredDuringSchedulingIgnoredDuringExecution:
#    - weight: 1
#      preference:
#        matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - rancher-work4


# ---------------------------------------------
#                 configmap
# ---------------------------------------------
configmap:
  enable: false
# data:
#   application.yaml: |
#     logging:
#       level: DEBUG
#     server:
#       port:8080


# ---------------------------------------------
#          PVC(PersistenceVolumeClaim)
# ---------------------------------------------
persistence:
  enabled: false
#  accessMode: ReadWriteOnce|ReadOnlyMany|ReadWriteMany
#  size: 100Gi
#  storageClass: nfs-client
