
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - svc.docker.okex.com
  http:
    paths:
    - backend:
        serviceName: ${CHART_NAME}
        servicePort: {{ .Values.service.port }}
      path: /${CHART_NAME}

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi